# Generated by Django 4.2.3 on 2023-07-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('can_see_results', 'See the counter of the transactions in the result screen'), ('can_consult_transaction', 'Consult the transaction to display the list of transactions'))},
        ),
    ]
